import type { UpgradeDefinition, UpgradeId } from './types';

/** Guaranteed and target-scope GameJam upgrades. Runtime state is stored separately. */
export const UPGRADE_DEFINITIONS = Object.freeze({
  silverBall: define({
    id: 'silverBall',
    name: 'Silver Ball',
    description: '+22% ball damage.',
    kind: 'weapon',
    maxStacks: 5,
    minPlayerLevel: 1,
    prerequisites: [],
    modifierPerStack: { ballDamageMultiplier: 0.22 },
  }),
  powerKick: define({
    id: 'powerKick',
    name: 'Power Kick',
    description: 'Harder, faster kicks with stronger knockback.',
    kind: 'weapon',
    maxStacks: 5,
    minPlayerLevel: 1,
    prerequisites: [],
    modifierPerStack: {
      kickPowerMultiplier: 0.16,
      ballSpeedMultiplier: 0.08,
      knockbackMultiplier: 0.15,
    },
  }),
  rapidRecall: define({
    id: 'rapidRecall',
    name: 'Rapid Recall',
    description: 'Recall the ball faster and more often.',
    kind: 'weapon',
    maxStacks: 4,
    minPlayerLevel: 1,
    prerequisites: [],
    modifierPerStack: {
      recallSpeedMultiplier: 0.18,
      recallCooldownMultiplier: -0.1,
    },
  }),
  piercingStuds: define({
    id: 'piercingStuds',
    name: 'Piercing Studs',
    description: 'The ball penetrates one additional enemy.',
    kind: 'weapon',
    maxStacks: 4,
    minPlayerLevel: 2,
    prerequisites: [{ upgradeId: 'silverBall', minStacks: 1 }],
    modifierPerStack: { pierceCount: 1 },
  }),
  garlicTrail: define({
    id: 'garlicTrail',
    name: 'Garlic Trail',
    description: 'The ball leaves a damaging garlic wake.',
    kind: 'weapon',
    maxStacks: 5,
    minPlayerLevel: 2,
    prerequisites: [],
    modifierPerStack: { garlicTrailDamage: 4 },
  }),
  orbitingSpectralBall: define({
    id: 'orbitingSpectralBall',
    name: 'Orbiting Spectral Ball',
    description: 'Summon a protective ball that circles the striker.',
    kind: 'weapon',
    maxStacks: 3,
    minPlayerLevel: 3,
    prerequisites: [],
    modifierPerStack: {
      orbitingBallCount: 1,
      orbitingBallDamage: 7,
    },
  }),
  bloodBomb: define({
    id: 'bloodBomb',
    name: 'Blood Bomb',
    description: 'Powerful impacts erupt in a blood explosion.',
    kind: 'weapon',
    maxStacks: 4,
    minPlayerLevel: 3,
    prerequisites: [{ upgradeId: 'powerKick', minStacks: 1 }],
    modifierPerStack: {
      bloodBombDamage: 8,
      bloodBombRadius: 0.35,
    },
  }),
  ghostPass: define({
    id: 'ghostPass',
    name: 'Ghost Pass',
    description: 'A spectral teammate duplicates a returning shot.',
    kind: 'weapon',
    maxStacks: 3,
    minPlayerLevel: 3,
    prerequisites: [{ upgradeId: 'rapidRecall', minStacks: 1 }],
    modifierPerStack: {
      ghostPassCount: 1,
      ghostPassDamageMultiplier: 0.12,
    },
  }),
  stormStuds: define({
    id: 'stormStuds',
    name: 'Storm Studs',
    description: 'Ball impacts arc lightning into nearby enemies.',
    kind: 'weapon',
    maxStacks: 4,
    minPlayerLevel: 3,
    prerequisites: [{ upgradeId: 'silverBall', minStacks: 1 }],
    modifierPerStack: {
      chainLightningDamage: 6,
      chainLightningTargets: 1,
    },
  }),
  frostCleats: define({
    id: 'frostCleats',
    name: 'Frost Cleats',
    description: 'Ball impacts burst with slowing grave-frost.',
    kind: 'weapon',
    maxStacks: 4,
    minPlayerLevel: 3,
    prerequisites: [{ upgradeId: 'rapidRecall', minStacks: 1 }],
    modifierPerStack: {
      frostBurstDamage: 5,
      frostBurstRadius: 0.25,
      frostSlowAmount: 0.1,
      frostSlowDuration: 0.45,
    },
  }),
  spectralVolley: define({
    id: 'spectralVolley',
    name: 'Spectral Volley',
    description: 'Ball impacts launch extra spectral shots in a fan.',
    kind: 'weapon',
    maxStacks: 4,
    minPlayerLevel: 4,
    prerequisites: [{ upgradeId: 'orbitingSpectralBall', minStacks: 1 }],
    modifierPerStack: {
      multiBallCount: 1,
      multiBallDamageMultiplier: 0.32,
    },
  }),
  voidGoal: define({
    id: 'voidGoal',
    name: 'Void Goal',
    description: 'Ball impacts open a temporary damaging gravity well.',
    kind: 'weapon',
    maxStacks: 4,
    minPlayerLevel: 5,
    prerequisites: [{ upgradeId: 'bloodBomb', minStacks: 1 }],
    modifierPerStack: {
      blackHoleDamage: 1.25,
      blackHoleRadius: 0.25,
      blackHolePullStrength: 3,
      blackHoleDuration: 0.8,
    },
  }),
  ironHeart: define({
    id: 'ironHeart',
    name: 'Iron Heart',
    description: '+12 maximum health. Gaining a stack also restores 12 health.',
    kind: 'passive',
    maxStacks: 5,
    minPlayerLevel: 1,
    prerequisites: [],
    modifierPerStack: { maxHealthBonus: 12 },
  }),
  bloodMagnet: define({
    id: 'bloodMagnet',
    name: 'Blood Magnet',
    description: '+20% Blood XP attraction range.',
    kind: 'passive',
    maxStacks: 5,
    minPlayerLevel: 1,
    prerequisites: [],
    modifierPerStack: { pickupRadiusMultiplier: 0.2 },
  }),
  killerInstinct: define({
    id: 'killerInstinct',
    name: 'Killer Instinct',
    description: '+8% damage from every source.',
    kind: 'passive',
    maxStacks: 5,
    minPlayerLevel: 1,
    prerequisites: [],
    modifierPerStack: { allDamageMultiplier: 0.08 },
  }),
  bloodDrinker: define({
    id: 'bloodDrinker',
    name: 'Blood Drinker',
    description: 'Defeated enemies and boss damage restore health, with a healing cap.',
    kind: 'passive',
    maxStacks: 5,
    minPlayerLevel: 2,
    prerequisites: [],
    modifierPerStack: {
      lifeStealOnPrimaryKill: 0.8,
      lifeStealOnSecondaryKill: 0.25,
      bossLifeStealRatio: 0.003,
    },
  }),
  dashShockwave: define({
    id: 'dashShockwave',
    name: 'Breakaway Shockwave',
    description: 'Every dash erupts in a damaging, knockback shockwave.',
    kind: 'weapon',
    maxStacks: 5,
    minPlayerLevel: 2,
    prerequisites: [],
    modifierPerStack: {
      dashShockwaveDamage: 6,
      dashShockwaveRadius: 0.32,
      dashShockwaveKnockback: 1.8,
    },
  }),
  consecratedPitch: define({
    id: 'consecratedPitch',
    name: 'Consecrated Pitch',
    description: 'Plant a pulsing penalty zone that burns vampires who enter it.',
    kind: 'weapon',
    maxStacks: 5,
    minPlayerLevel: 3,
    prerequisites: [],
    modifierPerStack: {
      holyZoneDamage: 2.5,
      holyZoneRadius: 0.25,
      holyZoneDuration: 0.7,
    },
  }),
  ricochetBall: define({
    id: 'ricochetBall',
    name: 'Bank Shot',
    description: 'Confirmed ball impacts bank into nearby targets with spectral force.',
    kind: 'weapon',
    maxStacks: 4,
    minPlayerLevel: 3,
    prerequisites: [{ upgradeId: 'piercingStuds', minStacks: 1 }],
    modifierPerStack: {
      ricochetDamage: 5,
      ricochetTargets: 1,
      ricochetRange: 0.4,
    },
  }),
  bloodBarrier: define({
    id: 'bloodBarrier',
    name: 'Blood Barrier',
    description: 'Gain a recharging ward that completely absorbs one incoming hit.',
    kind: 'passive',
    maxStacks: 3,
    minPlayerLevel: 2,
    prerequisites: [],
    modifierPerStack: {
      bloodBarrierCharges: 1,
      bloodBarrierRechargeMultiplier: -0.12,
    },
  }),
  headerCannon: define({
    id: 'headerCannon',
    name: 'Header Cannon',
    description: 'Charged kicks launch a crushing spectral header through the forward line.',
    kind: 'weapon',
    maxStacks: 5,
    minPlayerLevel: 2,
    prerequisites: [{ upgradeId: 'powerKick', minStacks: 1 }],
    modifierPerStack: {
      headerCannonDamage: 9,
      headerCannonRadius: 0.18,
      headerCannonKnockback: 1.4,
    },
  }),
  cornerStorm: define({
    id: 'cornerStorm',
    name: 'Corner Storm',
    description: 'Call down a rotating set-piece barrage around the nearest attackers.',
    kind: 'weapon',
    maxStacks: 4,
    minPlayerLevel: 4,
    prerequisites: [{ upgradeId: 'stormStuds', minStacks: 1 }],
    modifierPerStack: {
      cornerStormDamage: 7,
      cornerStormStrikes: 1,
      cornerStormInterval: -0.18,
    },
  }),
  redCard: define({
    id: 'redCard',
    name: 'Red Card',
    description: 'Periodically dismiss a weakened enemy and stun anything too strong to send off.',
    kind: 'weapon',
    maxStacks: 4,
    minPlayerLevel: 3,
    prerequisites: [],
    modifierPerStack: {
      redCardDamage: 7,
      redCardExecuteThreshold: 0.035,
      redCardStunDuration: 0.3,
    },
  }),
  spectralTeammate: define({
    id: 'spectralTeammate',
    name: 'Spectral Teammate',
    description: 'A phantom striker marks and volleys enemies beside you.',
    kind: 'weapon',
    maxStacks: 4,
    minPlayerLevel: 3,
    prerequisites: [{ upgradeId: 'ghostPass', minStacks: 1 }],
    modifierPerStack: {
      spectralTeammateCount: 1,
      spectralTeammateDamage: 6,
      spectralTeammateInterval: -0.12,
    },
  }),
  penaltyMine: define({
    id: 'penaltyMine',
    name: 'Penalty Mine',
    description: 'Plant cursed footballs that detonate when vampires enter the box.',
    kind: 'weapon',
    maxStacks: 4,
    minPlayerLevel: 3,
    prerequisites: [{ upgradeId: 'bloodBomb', minStacks: 1 }],
    modifierPerStack: {
      penaltyMineDamage: 11,
      penaltyMineRadius: 0.22,
      penaltyMineCount: 1,
    },
  }),
  bootCyclone: define({
    id: 'bootCyclone',
    name: 'Boot Cyclone',
    description: 'A ring of possessed boots sweeps nearby enemies off their feet.',
    kind: 'weapon',
    maxStacks: 5,
    minPlayerLevel: 2,
    prerequisites: [],
    modifierPerStack: {
      bootCycloneDamage: 3.5,
      bootCycloneRadius: 0.16,
      bootCycloneInterval: -0.08,
    },
  }),
} satisfies Record<UpgradeId, UpgradeDefinition>);

function define(definition: UpgradeDefinition): Readonly<UpgradeDefinition> {
  return Object.freeze({
    ...definition,
    prerequisites: Object.freeze(
      definition.prerequisites.map((requirement) => Object.freeze({ ...requirement })),
    ),
    modifierPerStack: Object.freeze({ ...definition.modifierPerStack }),
  });
}
